### ISSUE TITLE
does it works for zsh?

### ISSUE THREAD

**Issue by xjlin0** [martinsteinorth/getrbenv-installer#2]
Hi!  your app is so great like a breeze!

I used the "Configure your environment" option, without changing default installation directory(left empty), to get the following command:
````
curl -sSL http://getrbenv.com/install | bash -s -- --rubies 2.0.0-p598,2.2.2 --global-ruby 2.0.0-p598 --plugins sstephenson/ruby-build
````
However, I got an error message when I close/open shell "/home/j/.zshrc:83: command not found: rbenv", the environment of RBENV_ROOT= is empty, and the last 3 lines of my .zshrc is 
````
export RBENV_ROOT=${install_dir}
export PATH=${install_dir}/bin:$PATH
eval "$(rbenv init -)"
````
Did I do something wrong?  (rbenv is actually installed under ~/.rbenv and workable, just path setting problem)

**Comment by ryanjm** [comment]
Just tried running with zsh also. @xjlin0 did you find a work around?

I don't see any `bin` under `~/.rbenv`.

**Comment by xjlin0** [comment]
rbenv works, even with install plug-in.  http://xjlin0.github.io/tech/2015/04/14/babun-the-new-cygwin-for-ruby-rails-sinatra-and-nodejs/
![rbenv](https://cloud.githubusercontent.com/assets/8908273/7378883/8b8f5976-eda5-11e4-9231-65784696cc24.png)

**Comment by martinsteinorth** [comment]
Hey @xjlin0 and @ryanjm,

thanks for using the installer and sorry for the late response.

There was indeed a bug in the exports implementation that caused the zsh incompatibility. This should now be fixed, so I would be glad if you try again. Remember to close and reopen your shell after installation.

Keep in mind to uninstall any previous installations of rbenv by deleting the ~/.rbenv folder and removing all rbenv related commands from your shell config files (.zshrc, .bashrc etc.) to avoid duplicate commands. Support for detection of previous installations will be added in future versions.

**Comment by xjlin0** [comment]
Hey it almost works on zsh!!  The only small bug now is , at the second line of the .zshrc, instead of 

```
export PATH=/home/xjlin0/.rbenv/bin:$PATH
```

it was 

```
export PATH=/home/xjlin0/.rbenv/bin:/usr/sbin:/usr/local/bin.......(many many paths)
```

The installer actually interpolated $PATH and listed the many many path names and it didn't work.  Once I replaced all those many many path names  with the variable $PATH it worked.  So I add a backslash before $PATH to prevent  interpolate $PATH in install.sh line 256 to fix this bug. (pull requested) But I didn't tested on Bash.

```
    echo "export PATH=${install_dir}/bin:\$PATH" >> $DEFAULT_HOME_DIR/$file
```

<hr>

The following was the command I tested on Babun 1.1.

```
curl -sSL http://getrbenv.com/install | bash -s -- --rubies 2.0.0-p645 --local-rubies undefined@ --plugins sstephenson/ruby-build,rkh/rbenv-update
```

Another question, there's a small bug in current Ruby 2.2 causing the compilation in Cygwin failing, and a patch file is require.  Fortunately rbenv install born with the support of patch. <b>How can I modify the getrbenv installer commands to include the patch like the following?</b> Thanks

```
rbenv install --patch 2.2.0 < patch.filename
rbenv rehash
```

**Comment by xjlin0** [comment]
Hi Martin:
I found a way to bypass the patch things, so please ignore my above request regarding patch.  

However, it would be really great if easy rbenv installer can merge my pull request, which has one extra backslash to make it work under zsh.  Thanks!

![zshrbenv](https://cloud.githubusercontent.com/assets/8908273/7620622/10117bd0-f976-11e4-8652-e90f2ba28b1e.jpg)
